#+TITLE: Config
#+property: header-args:emacs-lisp :tangle "./config.el"

* Insight
This literal programmming style might be standard for me. I want to make a org file that
would leave snippets that worth left to make my own lisp library using asdf. That would
be real personal programming career for me at last!

* Bookmarks
#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix ("b". "buffer")
       :desc "List bookmarks" "L" #'list-bookmarks
       :desc "Save current bookmarks to bookmark file" "w" #'bookmark-save))
#+END_SRC

#+RESULTS:
: bookmark-save

* key-bindings
#+BEGIN_SRC emacs-lisp
(map! :leader
      :desc "shell"
      "s h" #'shell)

(map! :leader
      :desc "launch Web Browser with rich tools"
      "o w"#'xwidget-webkit-browse-url)

(map! :leader
      :desc "Org-roam-server"
      "r s" #'org-roam-server-mode)

(map! :leader
      :desc "run sly"
      "a" #'sly)

(map! :leader
      :desc "dmenu"
      "d" #'dmenu)

(map! :leader
      :desc "tangle"
      "o t" #'org-babel-tangle)

(map! :leader
      :desc "find-file"
      "f f" #'find-file)

(map! :leader
      :desc "open irb script"
      "r r" #'run-ruby)

(map! :leader
      :desc "org-table"
      "t o" #'org-table-create)

(map! :leader
      :desc "org-table"
      "e s" #'eshell)



#+END_SRC
* Theme
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-dracula)
#+END_SRC
* Langs and Dev
** LSP
*** gdscript-mode

#+begin_src emacs-lisp
(setq gdscript-godot-executable "/Users/yamamotoryuuji/desktop/Godot.app/contents/MacOS/Godot")
#+end_src
;; Runs the function `lsp--gdscript-ignore-errors` around `lsp--get-message-type` to suppress unknown notification errors.
#+BEGIN_SRC emacs-lisp
 (defun lsp--gdscript-ignore-errors (original-function &rest args)
  (if (string-equal major-mode "gdscript-mode")
      (let ((json-data (nth 0 args)))
        (if (and (string= (gethash "jsonrpc" json-data "") "2.0")
                 (not (gethash "id" json-data nil))
                 (not (gethash "method" json-data nil)))
            nil ; (message "Method not found")
          (apply original-function args)))
    (apply original-function args)))
(advice-add #'lsp--get-message-type :around #'lsp--gdscript-ignore-errors)

#+END_SRC
** TODO Debugging
I've figured out that from buffer list, I can read the some stderr.
It seems that I have same problem guys on the Github talked about.
#+begin_src emacs-lisp

(use-package dap-mode)

(require 'dap-chrome)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; (dap-register-debug-template "Debug react-native" ;;
;;     (list :type "chrome"                          ;;
;;           :cwd nil                                ;;
;;           :mode "url"                             ;;
;;           :reqest "launch"                        ;;
;;           :webRoot "~/Desktop/Tokyo100/"          ;;
;;           :url "http://localhost:19002"           ;;
;;           :name "Debug react-native"              ;;
;; ))                                                ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#+end_src
** CLISP
*** SLY
#+BEGIN_SRC emacs-lisp
(use-package sly)
#+END_SRC

* Org
** heads-up

** Directory
#+BEGIN_SRC emacs-lisp
(when (string-equal system-type "darwin")

(setq org-directory "~/MEGA/MEGAsync")

)
(when (string-equal system-type "gnu/linux")
(setq org-directory "~/MEGAsync")
)

#+END_SRC
** Journal
#+BEGIN_SRC emacs-lisp
(when (string-equal system-type "darwin")

(setq +org-capture-journal-file "~/MEGA/MEGAsync/journal" )

)
(when (string-equal system-type "gnu/linux")
(setq org-journal-dir "~/MEGAsync/journal" )
)


(setq org-journal-date-format "%A, %d %B %Y")
(require 'org-journal)

#+end_src
** Agenda
#+begin_src emacs-lisp
(setq org-agenda-skip-scheduled-if-done t
      org-agenda-skip-deadline-if-done t
      org-agenda-include-deadlines t
      org-agenda-block-separator #x2501
      org-agenda-compact-blocks t
      org-agenda-start-with-log-mode t)
(with-eval-after-load 'org-journal
(when (string-equal system-type "darwin")

  (setq org-agenda-files '("~/MEGA/MEGAsync/org"
                           "~/MEGA/MEGAsync/todo.org"
                           "~/MEGA/MEGAsync/journal.org"
                           "~/MEGA/MegaSyncFiles/todo.org"
                           )))

)
(when (string-equal system-type "gnu/linux")

  (setq org-agenda-files '("~/MEGAsync/org")))


(setq org-agenda-clockreport-parameter-plist
      (quote (:link t :maxlevel 5 :fileskip0 t :compact t :narrow 80)))
(setq org-agenda-deadline-faces
      '((1.0001 . org-warning)              ; due yesterday or before
        (0.0    . org-upcoming-deadline)))  ; due today or later

#+end_src

#+RESULTS:
: ((1.0001 . org-warning) (0.0 . org-upcoming-deadline))

**** agenda styles
#+begin_src emacs-lisp

#+end_src
** Org-roam-server
#+BEGIN_SRC emacs-lisp

(when (string-equal system-type "darwin")
 (setq org-roam-server-file-path "/Users/yamamotoryuuji/org-roam-server")
)
(when (string-equal system-type "gnu/linux")
 (setq org-roam-server-file-path "/home/ryu/org-roam-server")
)
(use-package org-roam-server
  :ensure t
  :load-path org-roam-server-file-path
  :config
  :init
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20)
)
#+END_SRC
** Pomodoro
#+BEGIN_SRC emacs-lisp
(use-package org-pomodoro
    :after org-agenda
    :custom
    (org-pomodoro-ask-upon-killing t)
    (org-pomodoro-format "%s")
    (org-pomodoro-short-break-format "%s")
    (org-pomodoro-long-break-format  "%s")
    :custom-face
    (org-pomodoro-mode-line ((t (:foreground "#ff5555"))))
    (org-pomodoro-mode-line-break   ((t (:foreground "#50fa7b"))))
    :hook
    (org-pomodoro-started . (lambda () (notifications-notify
                                               :title "org-pomodoro"
                           :body "Let's focus for 25 minutes!"
                           :app-icon "~/.emacs.d/img/001-food-and-restaurant.png")))
    (org-pomodoro-finished . (lambda () (notifications-notify
                                               :title "org-pomodoro"
                           :body "Well done! Take a break."
                           :app-icon "~/.emacs.d/img/004-beer.png")))
    :config
    :bind (:map org-agenda-mode-map
                ("p" . org-pomodoro)))

#+END_SRC
** Startup settings
#+begin_src emacs-lisp
(setq org-startup-folded t)

#+end_src
** Babel
*** Template
#+BEGIN_SRC emacs-lisp
(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("cl" . "src lisp"))
(add-to-list 'org-structure-template-alist '("aw" . "src awk"))
(add-to-list 'org-structure-template-alist '("sh" . "src sh"))
#+end_src

*** tangle
**** TODO Automatically tangle our Emacs.org config file when we save it
#+begin_src emacs-lisp

(defun efs/org-babel-tangle-config ()
  (when (string-equal (file-name-directory (buffer-file-name))
                      (expand-file-name "home/ryu/.doom.d/config.org"))
    ;; Dynamic scoping to the rescue
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))

(org-babel-do-load-languages
 'org-babel-load-languages
 '(lisp . t)
 '(awk . t)
 '(shell . t)
 )

#+end_src

#+RESULTS:
| (lambda nil (add-hook 'after-save-hook #'efs/org-babel-tangle-config)) | er/add-org-mode-expansions | +lookup--init-org-mode-handlers-h | (closure (t) (&rest _) (add-hook 'before-save-hook 'org-encrypt-entries nil t)) | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | (lambda (&rest _) #'(lambda nil (add-hook 'after-save-hook #'org-babel-tangle :append :local))) | doom-disable-show-paren-mode-h | doom-disable-show-trailing-whitespace-h | +org-enable-auto-reformat-tables-h | +org-enable-auto-update-cookies-h | +org-make-last-point-visible-h | evil-org-mode | toc-org-enable | embrace-org-mode-hook | org-eldoc-load |

* EXWM

** TODO exit the process where the current buffer exist.
#+begin_src emacs-lisp :tangle no
(require 'exwm)
(require 'exwm-config)
(exwm-config-default)
(require 'exwm-randr)

(setq exwm-randr-screen-change-hook
      (lambda ()
        (start-process-shell-command
         "xrandr" nil "xrandr --output Virtual-1 --mode 1366x768 --pos 0x0 --rotate normal")))
(exwm-randr-enable)
(require 'exwm-systemtray)

(exwm-systemtray-enable)
#+end_src
* GIT
#+begin_src emacs-lisp
(with-eval-after-load 'magit
  (require 'forge))
#+end_src
*

* TRANSPARE
#+begin_src emacs-lisp


#+end_src
