(deftheme yamamotoryuuji
  "Created 2022-05-13.")

(custom-theme-set-faces
 'yamamotoryuuji
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#282a36" :foreground "#f8f8f2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 240 :width normal :foundry "nil" :family "Menlo"))))
 '(cursor ((t (:background "#bd93f9"))))
 '(fixed-pitch ((t (:family "Menlo" :foundry "nil" :height 240))))
 '(variable-pitch ((t (:family "Helvetica" :foundry "nil" :height 240))))
 '(escape-glyph ((t (:foreground "#8be9fd"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#bd93f9"))))
 '(highlight ((t (:foreground "#1E2029" :background "#bd93f9"))))
 '(region ((t (:extend t :background "#44475a"))))
 '(shadow ((t (:foreground "#6272a4"))))
 '(secondary-selection ((t (:extend t :background "#565761"))))
 '(trailing-whitespace ((t (:background "#ff5555"))))
 '(font-lock-builtin-face ((t (:foreground "#ffb86c"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#ffb86c "))))
 '(font-lock-constant-face ((t (:foreground "#8be9fd"))))
 '(font-lock-doc-face ((t (:foreground "#8995ba" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:foreground "#50fa7b"))))
 '(font-lock-keyword-face ((t (:foreground "#ff79c6"))))
 '(font-lock-negation-char-face ((t (:foreground "#bd93f9" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#bd93f9" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#bd93f9" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#bd93f9" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#f1fa8c"))))
 '(font-lock-type-face ((t (:foreground "#bd93f9"))))
 '(font-lock-variable-name-face ((t (:foreground "#ffc9e8"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#bd93f9"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#565761" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#f8f8f2" :background "#1E2029"))))
 '(mode-line ((t (:box nil :background "#22232d"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#bd93f9"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#6272a4" :background "#252631"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#1E2029" :background "#ff5555"))))
 '(lazy-highlight ((t (:weight bold :foreground "#f8f8f2" :background "#8466ae"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(org-block ((t (:extend t :foreground "#bd93f9" :background "#23242f"))))
 '(org-block-begin-line ((t (:inherit org-block :extend t :background "#fF3f59b" :foreground "#6272a4"))))
 '(org-block-end-line ((t (:extend t :inherit (org-block-begin-line))))))

(provide-theme 'yamamotoryuuji)
